/*
 * Remoto - reading the profile
 *
 * The JSON reader is the same trick apps/clima/main/wx_api.c uses: it builds
 * no tree, it walks the text bounding ranges. Here a little more is needed
 * than over there because the profile nests (pages -> buttons -> action), so
 * there are two real primitives -"skip the value that starts here" and "find
 * this key inside this object"- and everything else comes out of those two.
 *
 * It is still far cheaper than putting cJSON into the firmware's symbol table,
 * and the JSON to be read is generated by our own web page: it is ASCII,
 * without comments and without numbers in scientific notation.
 *
 * No LVGL: it compiles with 'cc' for tools/rc_harness.c.
 */
#include "rc_model.h"
#include "aos_i18n.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* -------------------------------------------------------------------------- */
/* JSON                                                                        */
/* -------------------------------------------------------------------------- */

static const char *jx_ws(const char *p, const char *e)
{
    while (p < e && (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r')) {
        p++;
    }
    return p;
}

/* One byte past the value that starts at 'p'.
 *
 * Returns NULL if the value does not close. That distinction matters: a file
 * cut in half -the SD pulled out while the portal was writing- has unclosed
 * braces, and if this returned 'e' the profile would load with the pages that
 * made it to disk and nobody would find out. */
static const char *jx_end(const char *p, const char *e)
{
    if (p >= e) {
        return NULL;
    }
    if (*p == '"') {
        for (p++; p < e; p++) {
            if (*p == '\\') {
                p++;                        /* an escaped one never closes */
            } else if (*p == '"') {
                return p + 1;
            }
        }
        return NULL;
    }
    if (*p == '{' || *p == '[') {
        int depth = 0;
        bool in_str = false;
        for (; p < e; p++) {
            if (in_str) {
                if (*p == '\\') {
                    p++;
                } else if (*p == '"') {
                    in_str = false;
                }
                continue;
            }
            if (*p == '"') {
                in_str = true;
            } else if (*p == '{' || *p == '[') {
                depth++;
            } else if (*p == '}' || *p == ']') {
                if (--depth == 0) {
                    return p + 1;
                }
            }
        }
        return NULL;
    }
    /* number, true, false, null */
    while (p < e && *p != ',' && *p != '}' && *p != ']' &&
           *p != ' ' && *p != '\n' && *p != '\r' && *p != '\t') {
        p++;
    }
    return p;
}

/* Looks for 'key' among the members of the object starting at 'obj' (which
 * points at the opening brace). It only looks at the top level. */
static bool jx_get(const char *obj, const char *e, const char *key,
                   const char **vs, const char **ve)
{
    if (!obj || obj >= e || *obj != '{') {
        return false;
    }
    size_t klen = strlen(key);
    const char *p = jx_ws(obj + 1, e);

    while (p < e && *p == '"') {
        const char *ks = p + 1;
        const char *kend = jx_end(p, e);         /* points past the quote */
        if (!kend) {
            break;
        }
        size_t this_len = (size_t)(kend - 1 - ks);

        p = jx_ws(kend, e);
        if (p >= e || *p != ':') {
            break;
        }
        p = jx_ws(p + 1, e);
        const char *val_end = jx_end(p, e);
        if (!val_end) {
            break;
        }

        if (this_len == klen && memcmp(ks, key, klen) == 0) {
            *vs = p;
            *ve = val_end;
            return true;
        }
        p = jx_ws(val_end, e);
        if (p < e && *p == ',') {
            p = jx_ws(p + 1, e);
        } else {
            break;
        }
    }
    return false;
}

/* Distributes the elements of the array starting at 'arr'. Returns how many. */
static int jx_arr(const char *arr, const char *e,
                  const char **starts, const char **ends, int max)
{
    if (!arr || arr >= e || *arr != '[') {
        return 0;
    }
    int n = 0;
    const char *p = jx_ws(arr + 1, e);
    while (p < e && *p != ']' && n < max) {
        const char *item_end = jx_end(p, e);
        if (!item_end) {
            return 0;               /* an unclosed element: the array is no good */
        }
        starts[n] = p;
        ends[n]   = item_end;
        n++;
        p = jx_ws(item_end, e);
        if (p < e && *p == ',') {
            p = jx_ws(p + 1, e);
        } else {
            break;
        }
    }
    return n;
}

/* Copies an already unescaped JSON string, clipped to 'outlen'.
 *
 * Anything that is not printable ASCII is discarded: the font compiled into
 * the firmware is Montserrat with ASCII, so an accent that got this far would
 * be drawn as a square. The web page already strips them, this is the net. */
static void jx_str(const char *vs, const char *ve, char *out, int outlen)
{
    out[0] = 0;
    if (!vs || vs >= ve || *vs != '"') {
        return;
    }
    const char *p = vs + 1;
    const char *e = ve - 1;             /* the closing quote */
    int w = 0;

    while (p < e && w < outlen - 1) {
        char c = *p++;
        if (c == '\\' && p < e) {
            char x = *p++;
            switch (x) {
            case 'n': c = ' '; break;   /* a line break in a 20 px label
                                           contributes nothing */
            case 't': c = ' '; break;
            case 'r': continue;
            case 'b': continue;
            case 'f': continue;
            case 'u':
                /* \uXXXX: the code is skipped and whatever can be kept is kept */
                if (e - p >= 4) {
                    int v = 0;
                    for (int i = 0; i < 4; i++) {
                        char h = p[i];
                        int  d = (h >= '0' && h <= '9') ? h - '0'
                               : (h >= 'a' && h <= 'f') ? h - 'a' + 10
                               : (h >= 'A' && h <= 'F') ? h - 'A' + 10 : -1;
                        if (d < 0) { v = -1; break; }
                        v = v * 16 + d;
                    }
                    p += 4;
                    if (v < 0x20 || v > 0x7E) {
                        continue;
                    }
                    c = (char)v;
                } else {
                    continue;
                }
                break;
            default:  c = x; break;     /* " \ / and any other */
            }
        }
        if ((unsigned char)c < 0x20 || (unsigned char)c > 0x7E) {
            continue;
        }
        out[w++] = c;
    }
    out[w] = 0;
}

static long jx_int(const char *vs, const char *ve, long fallback)
{
    if (!vs || vs >= ve) {
        return fallback;
    }
    if (*vs == 't') {
        return 1;
    }
    if (*vs == 'f' || *vs == 'n') {
        return 0;
    }
    char tmp[24];
    int  n = (int)(ve - vs);
    if (n <= 0 || n >= (int)sizeof(tmp)) {
        return fallback;
    }
    memcpy(tmp, vs, (size_t)n);
    tmp[n] = 0;
    char *endp = NULL;
    long v = strtol(tmp, &endp, 10);
    return (endp && endp != tmp) ? v : fallback;
}

/* Shortcuts: find a key and convert it in one go. */
static void get_str(const char *obj, const char *e, const char *key,
                    char *out, int outlen)
{
    const char *vs, *ve;
    out[0] = 0;
    if (jx_get(obj, e, key, &vs, &ve)) {
        jx_str(vs, ve, out, outlen);
    }
}

static long get_int(const char *obj, const char *e, const char *key, long fallback)
{
    const char *vs, *ve;
    if (jx_get(obj, e, key, &vs, &ve)) {
        return jx_int(vs, ve, fallback);
    }
    return fallback;
}

/* -------------------------------------------------------------------------- */
/* State table                                                                 */
/* -------------------------------------------------------------------------- */

/* Registers an entity (with its attribute, if any) and returns its index, or
 * -1 if there is nothing to register or no more fit. Duplicates share a slot:
 * half a dozen buttons on the same light are ONE query. */
static int state_slot(rc_profile_t *p, const char *entity, const char *attr)
{
    if (!entity || !entity[0]) {
        return -1;
    }
    for (int i = 0; i < p->n_states; i++) {
        if (strcmp(p->st_entity[i], entity) == 0 &&
            strcmp(p->st_attr[i], attr ? attr : "") == 0) {
            return i;
        }
    }
    if (p->n_states >= RC_MAX_STATES) {
        return -1;
    }
    int i = p->n_states++;
    snprintf(p->st_entity[i], RC_LEN_ENTITY, "%s", entity);
    snprintf(p->st_attr[i], RC_LEN_ATTR, "%s", attr ? attr : "");
    p->st_value[i][0] = 0;
    return i;
}

const char *rc_state_value(const rc_profile_t *p, int slot)
{
    if (!p || slot < 0 || slot >= p->n_states) {
        return "";
    }
    return p->st_value[slot];
}

bool rc_state_is_on(const rc_profile_t *p, int slot)
{
    const char *v = rc_state_value(p, slot);
    return strcmp(v, "on") == 0 || strcmp(v, "home") == 0 ||
           strcmp(v, "open") == 0 || strcmp(v, "playing") == 0 ||
           strcmp(v, "heat") == 0 || strcmp(v, "cool") == 0 ||
           strcmp(v, "unlocked") == 0;
}

/* -------------------------------------------------------------------------- */
/* Parsing the profile                                                         */
/* -------------------------------------------------------------------------- */

static void parse_action(const char *obj, const char *e, rc_action_t *a)
{
    memset(a, 0, sizeof(*a));
    if (!obj || obj >= e || *obj != '{') {
        return;
    }
    char type[12];
    get_str(obj, e, "t", type, sizeof(type));

    if (strcmp(type, "page") == 0) {
        a->type = RC_ACT_PAGE;
        a->page = (int16_t)get_int(obj, e, "p", 0);
        return;
    }
    if (strcmp(type, "svc") != 0) {
        return;                             /* "" or unknown = does nothing */
    }
    get_str(obj, e, "s", a->service, sizeof(a->service));
    if (!a->service[0]) {
        return;
    }
    a->type = RC_ACT_SERVICE;
    get_str(obj, e, "e", a->entity, sizeof(a->entity));
    get_str(obj, e, "d", a->data, sizeof(a->data));
}

static void parse_button(rc_profile_t *p, const char *obj, const char *e,
                         rc_button_t *b)
{
    memset(b, 0, sizeof(*b));
    b->slot  = -1;
    b->color = 0x0A84FF;

    get_str(obj, e, "l", b->label, sizeof(b->label));
    get_str(obj, e, "i", b->icon, sizeof(b->icon));
    b->color = (uint32_t)get_int(obj, e, "c", 0x0A84FF) & 0xFFFFFFu;

    const char *vs, *ve;
    if (jx_get(obj, e, "a", &vs, &ve)) {
        parse_action(vs, ve, &b->tap);
    }
    if (jx_get(obj, e, "h", &vs, &ve)) {
        parse_action(vs, ve, &b->hold);
    }

    b->st_mode = (uint8_t)get_int(obj, e, "sm", RC_ST_NONE);
    get_str(obj, e, "st", b->st_entity, sizeof(b->st_entity));
    get_str(obj, e, "sa", b->st_attr, sizeof(b->st_attr));
    get_str(obj, e, "u", b->unit, sizeof(b->unit));

    if (b->st_mode == RC_ST_NONE || !b->st_entity[0]) {
        b->st_mode = RC_ST_NONE;
        return;
    }
    if (b->st_mode != RC_ST_ATTR) {
        b->st_attr[0] = 0;
    }
    b->slot = (int8_t)state_slot(p, b->st_entity, b->st_attr);
    if (b->slot < 0) {
        b->st_mode = RC_ST_NONE;        /* the table filled up: better with no
                                           ornament than with a value that never arrives */
    }
}

static void parse_dial(rc_profile_t *p, const char *obj, const char *e,
                       rc_dial_t *d)
{
    memset(d, 0, sizeof(*d));
    d->slot     = -1;
    d->min      = 1;
    d->max      = 100;
    d->span_deg = 120;
    d->st_full  = 100;

    if (!obj || obj >= e || *obj != '{') {
        return;
    }
    get_str(obj, e, "s", d->service, sizeof(d->service));
    get_str(obj, e, "e", d->entity, sizeof(d->entity));
    get_str(obj, e, "f", d->field, sizeof(d->field));
    d->min      = (int16_t)get_int(obj, e, "mn", 1);
    d->max      = (int16_t)get_int(obj, e, "mx", 100);
    d->span_deg = (uint16_t)get_int(obj, e, "sp", 120);
    d->invert   = (uint8_t)(get_int(obj, e, "inv", 0) ? 1 : 0);
    d->live_ms  = (uint16_t)get_int(obj, e, "live", 300);

    get_str(obj, e, "st", d->st_entity, sizeof(d->st_entity));
    get_str(obj, e, "sa", d->st_attr, sizeof(d->st_attr));
    d->st_full  = (int16_t)get_int(obj, e, "sf", 100);

    if (d->max <= d->min) {
        d->max = (int16_t)(d->min + 1);
    }
    if (d->span_deg < 30) {
        d->span_deg = 30;
    }
    if (d->span_deg > 300) {
        d->span_deg = 300;
    }
    if (d->st_full <= 0) {
        d->st_full = 100;
    }
    if (d->st_entity[0]) {
        d->slot = (int8_t)state_slot(p, d->st_entity, d->st_attr);
    }
}

static void parse_page(rc_profile_t *p, const char *obj, const char *e,
                       rc_page_t *pg)
{
    memset(pg, 0, sizeof(*pg));
    get_str(obj, e, "n", pg->name, sizeof(pg->name));

    char kind[8];
    get_str(obj, e, "k", kind, sizeof(kind));
    pg->kind = (strcmp(kind, "dial") == 0) ? RC_PAGE_DIAL : RC_PAGE_GRID;

    const char *vs, *ve;
    if (pg->kind == RC_PAGE_DIAL) {
        if (jx_get(obj, e, "dl", &vs, &ve)) {
            parse_dial(p, vs, ve, &pg->dial);
        } else {
            parse_dial(p, NULL, NULL, &pg->dial);
        }
        return;
    }

    pg->cols = (uint8_t)get_int(obj, e, "c", 3);
    pg->rows = (uint8_t)get_int(obj, e, "r", 3);
    if (pg->cols < 1 || pg->cols > 3) {
        pg->cols = 3;
    }
    if (pg->rows < 1 || pg->rows > 3) {
        pg->rows = 3;
    }

    if (!jx_get(obj, e, "b", &vs, &ve)) {
        return;
    }
    const char *starts[RC_MAX_BUTTONS], *ends[RC_MAX_BUTTONS];
    int n = jx_arr(vs, ve, starts, ends, RC_MAX_BUTTONS);

    int cap = pg->cols * pg->rows;
    if (n > cap) {
        n = cap;
    }
    for (int i = 0; i < n; i++) {
        parse_button(p, starts[i], ends[i], &pg->btn[i]);
    }
    pg->count = (uint8_t)n;
}

rc_profile_t *rc_parse(const char *json, int len, char *err, int errlen)
{
    if (err && errlen > 0) {
        err[0] = 0;
    }
    if (!json || len <= 0) {
        if (err) snprintf(err, errlen, "%s", _("archivo vacio"));
        return NULL;
    }

    const char *e   = json + len;
    const char *obj = jx_ws(json, e);
    if (obj >= e || *obj != '{') {
        if (err) snprintf(err, errlen, "%s", _("no empieza con {"));
        return NULL;
    }

    const char *vs, *ve;
    if (!jx_get(obj, e, "pages", &vs, &ve) || *vs != '[') {
        if (err) snprintf(err, errlen, "%s", _("falta la lista 'pages'"));
        return NULL;
    }

    const char *starts[RC_MAX_PAGES], *ends[RC_MAX_PAGES];
    int n = jx_arr(vs, ve, starts, ends, RC_MAX_PAGES);
    if (n <= 0) {
        if (err) snprintf(err, errlen, "%s", _("no hay ninguna pagina"));
        return NULL;
    }

    rc_profile_t *p = calloc(1, sizeof(*p));
    if (!p) {
        if (err) snprintf(err, errlen, "%s", _("sin memoria"));
        return NULL;
    }
    p->pages = calloc((size_t)n, sizeof(rc_page_t));
    if (!p->pages) {
        free(p);
        if (err) snprintf(err, errlen, _("sin memoria para %d paginas"), n);
        return NULL;
    }

    p->version = (int)get_int(obj, e, "v", 1);
    p->poll_s  = (uint16_t)get_int(obj, e, "poll", 5);
    if (p->poll_s && p->poll_s < 2) {
        p->poll_s = 2;              /* each request takes ~1 s: there is no
                                       point asking more often */
    }

    /* Gesture settings, with conservative defaults: better that firing one is
     * hard than that the lights come on in your pocket. */
    p->gcfg.enabled  = 1;
    p->gcfg.shake_mg = 2000;
    p->gcfg.tilt_deg = 40;
    p->gcfg.hold_ms  = 700;
    p->gcfg.cool_ms  = 1500;

    if (jx_get(obj, e, "gcfg", &vs, &ve)) {
        p->gcfg.enabled  = (uint8_t)(get_int(vs, ve, "on", 1) ? 1 : 0);
        p->gcfg.shake_mg = (int16_t)get_int(vs, ve, "shake", 2000);
        p->gcfg.tilt_deg = (int16_t)get_int(vs, ve, "tilt", 40);
        p->gcfg.hold_ms  = (uint16_t)get_int(vs, ve, "hold", 700);
        p->gcfg.cool_ms  = (uint16_t)get_int(vs, ve, "cool", 1500);
        if (p->gcfg.shake_mg < 200)  p->gcfg.shake_mg = 200;
        if (p->gcfg.tilt_deg < 15)   p->gcfg.tilt_deg = 15;
        if (p->gcfg.tilt_deg > 80)   p->gcfg.tilt_deg = 80;
        if (p->gcfg.cool_ms  < 300)  p->gcfg.cool_ms  = 300;
    }

    if (jx_get(obj, e, "gestures", &vs, &ve)) {
        static const char *const keys[RC_G_COUNT] = {
            "shake", "tiltl", "tiltr", "tiltf", "tiltb", "flip"
        };
        for (int g = 0; g < RC_G_COUNT; g++) {
            const char *as, *ae;
            if (jx_get(vs, ve, keys[g], &as, &ae)) {
                parse_action(as, ae, &p->gest[g]);
            }
        }
    }

    for (int i = 0; i < n; i++) {
        parse_page(p, starts[i], ends[i], &p->pages[i]);
    }
    p->n_pages = (uint8_t)n;

    /* A page action pointing outside is a configuration error that on screen
     * would look like a button that does nothing. It is clamped. */
    for (int i = 0; i < n; i++) {
        for (int b = 0; b < p->pages[i].count; b++) {
            rc_action_t *acts[2] = { &p->pages[i].btn[b].tap,
                                     &p->pages[i].btn[b].hold };
            for (int k = 0; k < 2; k++) {
                if (acts[k]->type == RC_ACT_PAGE &&
                    (acts[k]->page < 0 || acts[k]->page >= n)) {
                    acts[k]->type = RC_ACT_NONE;
                }
            }
        }
    }
    return p;
}

rc_profile_t *rc_load(const char *path, char *err, int errlen)
{
    if (err && errlen > 0) {
        err[0] = 0;
    }
    FILE *f = fopen(path, "rb");
    if (!f) {
        if (err) snprintf(err, errlen, _("no encontre %s"), path);
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    rewind(f);

    if (size <= 1 || size > 64 * 1024) {
        fclose(f);
        if (err) snprintf(err, errlen, _("tamano raro: %ld bytes"), size);
        return NULL;
    }
    char *buf = malloc((size_t)size + 1);
    if (!buf) {
        fclose(f);
        if (err) snprintf(err, errlen, _("sin memoria para %ld bytes"), size);
        return NULL;
    }
    size_t got = fread(buf, 1, (size_t)size, f);
    fclose(f);
    buf[got] = 0;

    rc_profile_t *p = rc_parse(buf, (int)got, err, errlen);
    free(buf);
    return p;
}

void rc_free(rc_profile_t *p)
{
    if (!p) {
        return;
    }
    free(p->pages);
    free(p);
}

/* -------------------------------------------------------------------------- */
/* State template                                                              */
/* -------------------------------------------------------------------------- */

char *rc_build_template(const rc_profile_t *p)
{
    if (!p || p->n_states == 0) {
        return NULL;
    }
    /* The real ceiling: 40 entries of 64+24 characters plus the wrapper. */
    size_t cap = (size_t)p->n_states * (RC_LEN_ENTITY + RC_LEN_ATTR + 40) + 8;
    char  *out = malloc(cap);
    if (!out) {
        return NULL;
    }
    size_t w = 0;
    for (int i = 0; i < p->n_states; i++) {
        if (i) {
            out[w++] = '|';
        }
        int n;
        if (p->st_attr[i][0]) {
            n = snprintf(out + w, cap - w, "{{state_attr('%s','%s')}}",
                         p->st_entity[i], p->st_attr[i]);
        } else {
            n = snprintf(out + w, cap - w, "{{states('%s')}}", p->st_entity[i]);
        }
        if (n <= 0 || (size_t)n >= cap - w) {
            break;
        }
        w += (size_t)n;
    }
    out[w] = 0;
    return out;
}

void rc_apply_template(rc_profile_t *p, const char *body, int len)
{
    if (!p || !body || len <= 0) {
        return;
    }
    int i = 0;
    const char *s = body;
    const char *e = body + len;

    /* Home Assistant answers plain text; it may bring a trailing line break
     * and, if something went wrong, a message with no slashes in it. In that
     * case the leftover entries stay as they were instead of being wiped. */
    while (s < e && i < p->n_states) {
        const char *bar = s;
        while (bar < e && *bar != '|') {
            bar++;
        }
        int n = (int)(bar - s);
        while (n > 0 && (s[n - 1] == '\n' || s[n - 1] == '\r' || s[n - 1] == ' ')) {
            n--;
        }
        while (n > 0 && *s == ' ') {
            s++;
            n--;
        }
        if (n >= RC_LEN_VALUE) {
            n = RC_LEN_VALUE - 1;
        }
        memcpy(p->st_value[i], s, (size_t)n);
        p->st_value[i][n] = 0;
        i++;

        if (bar >= e) {
            break;
        }
        s = bar + 1;
    }
    if (i > 0) {
        p->st_valid = true;
    }
}

/* -------------------------------------------------------------------------- */
/* Actions                                                                     */
/* -------------------------------------------------------------------------- */

bool rc_split_service(const char *service, char *domain, int dlen,
                      char *name, int nlen)
{
    if (!service) {
        return false;
    }
    const char *dot = strchr(service, '.');
    if (!dot || dot == service || !dot[1]) {
        return false;
    }
    int n = (int)(dot - service);
    if (n >= dlen) {
        return false;
    }
    memcpy(domain, service, (size_t)n);
    domain[n] = 0;
    snprintf(name, nlen, "%s", dot + 1);
    return true;
}

int rc_action_body(const rc_action_t *a, char *out, int outlen)
{
    int n;
    if (a->entity[0] && a->data[0]) {
        n = snprintf(out, outlen, "{\"entity_id\":\"%s\",%s}", a->entity, a->data);
    } else if (a->entity[0]) {
        n = snprintf(out, outlen, "{\"entity_id\":\"%s\"}", a->entity);
    } else if (a->data[0]) {
        n = snprintf(out, outlen, "{%s}", a->data);
    } else {
        n = snprintf(out, outlen, "{}");
    }
    if (n < 0 || n >= outlen) {
        snprintf(out, outlen, "{}");
        return 2;
    }
    return n;
}

const char *rc_gesture_name(int g)
{
    switch (g) {
    case RC_G_SHAKE:  return "sacudida";
    case RC_G_TILT_L: return _("a la izquierda");
    case RC_G_TILT_R: return _("a la derecha");
    case RC_G_TILT_F: return _("hacia adelante");
    case RC_G_TILT_B: return _("hacia atras");
    case RC_G_FLIP:   return _("boca abajo");
    default:          return "?";
    }
}
