/*
 * AmoledOS font set - generated by tools/gen_fonts.py, do not edit.
 *
 * Montserrat Medium with the Latin-1 supplement, so accented text
 * renders. LVGL's own lv_font_montserrat_* are ASCII only and stay
 * compiled in for the dynamic apps that reference them directly.
 *
 * Do not name these fonts in UI code. Go through the role pointers
 * in aos_theme.h (aos_font_huge / title / body / small) so that a
 * language switch can repoint them in one place.
 */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(aos_montserrat_14);
LV_FONT_DECLARE(aos_montserrat_16);
LV_FONT_DECLARE(aos_montserrat_20);
LV_FONT_DECLARE(aos_montserrat_28);
LV_FONT_DECLARE(aos_montserrat_36);
LV_FONT_DECLARE(aos_montserrat_48);

#ifdef __cplusplus
}
#endif
