#!/usr/bin/env python3
"""The BLE app's own glyphs: a small Material Design Icons font in the .so.

AmoledOS has no system glyph font an app can use (the firmware's MDI fonts are
the folders' and Settings' own), so the app brings the few it draws: the
device classes, and the screens' small icons. The names are P4OS's AOS_SYM_*
ones on purpose, so the screens ported from there read the same.

Writes main/bl_sym_s.c and main/bl_sym_l.c (the two fonts, 4 bpp) and
main/bl_glyphs.h. Needs lv_font_conv (npm install -g lv_font_conv) and the
MDI files that tools/gen_folder_glyphs.py keeps in ~/.cache/amoledos-mdi.

Usage: python3 apps/ble/tools/gen_glyphs.py
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MAIN = os.path.join(HERE, "..", "main")
CACHE = os.path.expanduser("~/.cache/amoledos-mdi/7.4.47")

SIZES = [("bl_sym_s", 24), ("bl_sym_l", 44)]

NAMES = [
    "alert-outline", "bluetooth", "bluetooth-off", "chart-areaspline", "chevron-left",
    "chevron-right", "clock-outline", "cog", "delete", "developer-board", "download",
    "gamepad-variant", "information-outline", "keyboard", "lan-connect", "lan-disconnect",
    "lightbulb", "lock-open-variant", "magnify", "monitor", "music", "pause", "pencil",
    "phone", "pin", "play", "pulse", "radar", "speedometer", "star", "star-outline",
    "television", "thermometer", "volume-high", "volume-off", "water-percent",
    "format-list-bulleted", "crosshairs-gps", "access-point",
]


def main():
    meta = json.load(open(os.path.join(CACHE, "meta.json")))
    by_name = {m["name"]: int(m["codepoint"], 16) for m in meta}
    missing = [n for n in NAMES if n not in by_name]
    if missing:
        sys.exit("not in MDI: " + ", ".join(missing))
    cps = ",".join("0x%X" % by_name[n] for n in NAMES)
    # one file per size: lv_font_conv's tables are statics with fixed names
    for font, px in SIZES:
        out = os.path.join(MAIN, font + ".c")
        subprocess.check_call([
            "lv_font_conv", "--no-compress", "--no-prefilter", "--bpp", "4", "--size", str(px),
            "--format", "lvgl", "--font", os.path.join(CACHE, "mdi.ttf"), "-r", cps,
            "--lv-font-name", font, "--lv-include", "lvgl.h", "-o", out])
        # the command line lv_font_conv writes in its header, without this
        # Mac's paths
        body = open(out).read().replace(CACHE, "~/.cache/amoledos-mdi/7.4.47").replace(out, font + ".c")
        with open(out, "w") as f:
            f.write("/* Generated by apps/ble/tools/gen_glyphs.py from Material Design Icons\n"
                    " * 7.4.47 (Pictogrammers Free License). Do not edit. */\n")
            f.write(body)
    with open(os.path.join(MAIN, "bl_glyphs.h"), "w") as f:
        f.write("/* Generated by apps/ble/tools/gen_glyphs.py. Do not edit.\n"
                " * Each glyph as UTF-8, for a label in bl_sym_s (24 px) or bl_sym_l (44 px). */\n"
                "#pragma once\n\n#include \"lvgl.h\"\n\n"
                "LV_FONT_DECLARE(bl_sym_s);\nLV_FONT_DECLARE(bl_sym_l);\n\n")
        for n in NAMES:
            s = chr(by_name[n]).encode("utf-8")
            f.write('#define AOS_SYM_%-24s "%s"\n' % (n.upper().replace("-", "_"),
                                                    "".join("\\x%02X" % b for b in s)))


if __name__ == "__main__":
    main()
